[package]
name = "icao-api"
version = "0.1.1"
edition = "2021"

[dependencies]
actix-web = "4.10.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
csv = "1.3.1"
thiserror = "2.0.12"
log = "0.4.27"
env_logger = "0.11.8"
rayon = "1.10.0"
